tasks:
  - init: echo "Replace me with a build script for the project."
    command: klayout &
image: lewisyuan/masklayout
#   file: .gitpod.Dockerfile
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview

vscode:
  extensions:
    - twxs.cmake@0.0.17:9s7m9CWOr6i6NZ7CNNF4kw==
    - ms-vscode.cmake-tools@1.4.0:eP3hU/MFme+CcSL21Klk1w==
